In [3]:
import numpy as np


In [4]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [5]:
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [6]:
profir_loss=revenue-expenses

In [7]:
profir_loss

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [8]:
#unit sold

In [9]:
price=np.array([1000,400,1200])
price


array([1000,  400, 1200])

In [10]:
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [12]:
total_sales=price*units
total_sales

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [18]:
total_sales=np.dot(price,units)
total_sales

array([34400, 50000, 64400])

In [21]:
revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [22]:
converted_revenue=revenue*75

In [23]:
converted_revenue

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])